"""Single source of truth for runtime trace protocol constants."""

TRACE_SCHEMA_ID = "zerorod-analysis/runtime-trace/v1"

TRACE_ENABLE_ENV = "ZEROROD_RUNTIME_TRACE"
TRACE_RAW_PATH_ENV = "ZEROROD_RUNTIME_TRACE_RAW_PATH"
TRACE_BUNDLE_ROOT_ENV = "ZEROROD_RUNTIME_TRACE_BUNDLE_ROOT"
TRACE_PROFILE_ENV = "ZEROROD_RUNTIME_TRACE_PROFILE"
TRACE_STIMULUS_DIR_ENV = "ZEROROD_RUNTIME_TRACE_STIMULUS_DIR"

PROFILE_STARTUP_TEST = "startup-test"
PROFILE_PREVIEW_PROBE = "preview-probe"
PROFILE_EXPORT_PROBE = "export-probe"
TRACE_PROFILES = (PROFILE_STARTUP_TEST, PROFILE_PREVIEW_PROBE, PROFILE_EXPORT_PROBE)
